import React, { Component } from 'react'
import Upper from './LeftMenu/Upper'
import Lower from './LeftMenu/Lower/Lower'
import './LeftMenu/LeftMenu.css'
export default class LeftMenu extends Component {
    render() {
        return (
            <div>
            <Upper/>
            <br/>
            <div className="center-col">
            <Lower/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
            </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
            </div>
        )
    }
}